# Generated by Django 4.0.4 on 2022-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity_index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
