# Generated by Django 4.0.4 on 2022-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_popularity_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='name',
            new_name='show_time',
        ),
        migrations.AlterField(
            model_name='shows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
