# Generated by Django 4.0.4 on 2022-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_name_shows_show_time_alter_shows_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='datetime',
        ),
        migrations.AddField(
            model_name='shows',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
