# Generated by Django 4.0.4 on 2022-06-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_shows_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booked_seats',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='movie_shown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='movie.theater'),
        ),
    ]
